### ISSUE TITLE
Get  ModuleNotFoundError: No module named 'onnxruntime' 

### ISSUE THREAD

**Issue by tobecrazy** [facefusion/facefusion-docker#16]
Hi guys,

I try the README instruction but failed to up the container
Run: `docker-compose -f docker-compose.cpu.yml up`  , get below errors:

2023-12-10 16:53:01 facefusion-docker-facefusion-cpu-1  | Traceback (most recent call last):
2023-12-10 16:53:01 facefusion-docker-facefusion-cpu-1  |   File "/facefusion/run.py", line 3, in <module>
2023-12-10 16:53:01 facefusion-docker-facefusion-cpu-1  |     from facefusion import core
2023-12-10 16:53:01 facefusion-docker-facefusion-cpu-1  |   File "/facefusion/facefusion/core.py", line 10, in <module>
2023-12-10 16:53:01 facefusion-docker-facefusion-cpu-1  |     import onnxruntime
2023-12-10 16:53:01 facefusion-docker-facefusion-cpu-1  | ModuleNotFoundError: No module named 'onnxruntime'

Docker version:  4.20.1 (110738)

OS: MacOS 14.1.2 (23B92)
CPU chip: Intel i9

**Comment by henryruhs** [comment]
I guess you need to adjust the Dockerfile. You better join our Discord for troubleshooting, GitHub is not suitable for that.

```
RUN python install.py --torch default --onnxruntime default
```
